#!/usr/bin/env bash
# meant to be passed a ssh record generated by get_interfaces.
# will export username and ip needed for ssh connection
choose_ip() {
    local file="$1"
    
    # Get username from first line
    username=$(sed -n '1p' "$file")
    echo "$username" >&2
    # Show the file (skip first line - username)
    tail -n +2 "$file" >&2 
    
    # Get user choice
    echo -n "Choose line number: " >&2
    read -r line_number
    
    # Get the IP from that line (add 1 to account for skipped first line)
    ip=$(sed -n "$((line_number + 1))p" "$file" | cut -d' ' -f2)
    # sed extracts the specific line number, cut splits on space and takes field 2 (the IP)
    
    echo "Selected: $username@$ip" >&2
    
    # Export for use elsewhere
    echo "$username"
    echo "$ip"
}

# Usage
choose_ip "$1"
#printf "%s\n" "$SELECTED_USER" "$SELECTED_IP"

