#!/usr/bin/env bash
# meant to be passed a ssh record generated by get_interfaces.
# will export username and ip needed for ssh connection

choose_ip() {
    local file="$1"
    
    # Validate file exists
    if [[ ! -f "$file" ]]; then
        echo "Error: File '$file' not found" >&2
        return 1
    fi
    
    # Get username from first line
    username=$(sed -n '1p' "$file")
    
    # Validate username exists
    if [[ -z "$username" ]]; then
        echo "Error: No username found in file" >&2
        return 1
    fi
    
    # Show the file (skip first line - username)
    echo "Available Interfaces:" >&2
    tail -n +2 "$file" | nl >&2 
    echo "" >&2
    
    # Get total number of available interfaces
    # all but first line is interfaces
    # tail it starting from th esecond line
    # then word count -l (lines)
    total_lines=$(tail -n +2 "$file" | wc -l)
    
    if [[ "$total_lines" -eq 0 ]]; then
        echo "Error: No interfaces found in file" >&2
        return 1
    fi
    
    # Get user choice with validation
    while true; do
        echo -n "Choose line number (1-$total_lines): " >&2
        read -r line_number
        
        # Check if input is a number
        if [[ "$line_number" =~ ^[0-9]+$ ]]; then
            # Check if number is in valid range
            if [[ "$line_number" -ge 1 && "$line_number" -le "$total_lines" ]]; then
                break
            else
                echo "Error: Please enter a number between 1 and $total_lines" >&2
            fi
        else
            echo "Error: Please enter a valid number" >&2
        fi
    done
    
    # Get the IP from that line (add 1 to account for skipped first line)
    # Extract IP: sed -n (quiet mode) + p (print line), then cut -d (delimiter) -f (field)
    # Get line (user_choice + 1), split on space, take field 2
    ip=$(sed -n "$((line_number + 1))p" "$file" | cut -d' ' -f2)
    
    # Validate IP was found
    if [[ -z "$ip" ]]; then
        echo "Error: Could not extract IP address" >&2
        return 1
    fi
    
    # REMOVED DEBUG OUTPUT - these were cluttering the interface
    # echo "Selected: $username@$ip" >&2
    
    # Export for use elsewhere
    echo "$username"
    echo "$ip"
}

# Usage
choose_ip "$1"